security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: 3600000

server:
  port: 8081
  servlet:
    context-path: /bootcamp-tracker-dev

spring:
  web:
    resources:
      add-mappings: false
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootcamp_tracker_dev?useTimezone=true&serverTimezone=UTC
    username: ${DEV-DB-USERNAME}
    password: ${DEV-DB-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:/db/migration, classpath:/test/db/migration, classpath:/sec/db/migration

spring-doc:
  paths-to-match: /v1/**
  swagger-ui:
    use-root-path: true