server:
  port: 8080
  servlet:
    context-path: /bootcamp-tracker

spring:
  web:
    resources:
      add-mappings: false
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootcamp_tracker?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:/db/migration

spring-doc:
  paths-to-match: /v1/**
  swagger-ui:
    use-root-path: true
    defaultModelsExpandDepth: -1