server:
  port: 8081
  servlet:
    context-path: /bootcamp-tracker

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootcamp_tracker?useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: ${PWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always