spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
    initialize: true
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always